### ISSUE TITLE
SE Linux prevents binding in home folder

### ISSUE THREAD

**Issue by buvoli** [container-job-runner/cjr#35]
Bind mounts in the home directory In Fedora 30 are no visible to the container when running cjr shell command due to SE Linux. This is remediable by adding the flag --security-opt label=disable

Related: https://github.com/containers/libpod/issues/3683

**Comment by stolotti** [comment]
I also suggest to use:
    user: "${UID}:${GID}"
    security_opt:
      - label=disable
    volumes:
      - ./app:/var/www/fe

in docker-compose/container-compose file.
